// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type MsgDatum struct {
	MessageID int    `json:"message_id"`
	UserID    int64  `json:"user_id"`
	Search    string `json:"search"`
	Year      string `json:"year"`
	Category  string `json:"category"`
}

type NzbInfo struct {
	ID          string `json:"id"`
	Url         string `json:"url"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	SabnzbdID   string `json:"sabnzbd_id"`
	ChatID      int64  `json:"chat_id"`
	MessageID   int    `json:"message_id"`
	Status      string `json:"status"`
	LastUpdated int64  `json:"last_updated"`
	Selected    int    `json:"selected"`
}
